{{- if .Values.controller.enabled }}
kind: Deployment
apiVersion: apps/v1
metadata:
  annotations:
    reloader.stakater.com/auto: "true"
  name: synthetic-pop-controller
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "synthetic-pop.commonLabels" . | nindent 4 }}
    app: synthetic-pop
    app.kubernetes.io/name: controller
    component: synthetic-pop-controller
spec:
  selector:
    matchLabels:
      {{- include "synthetic-pop.selectorLabels" . | nindent 6 }}
      app: synthetic-pop
      app.kubernetes.io/name: controller
      component: synthetic-pop-controller
  replicas: 1
  template:
    metadata:
      labels:
        {{- include "synthetic-pop.commonLabels" . | nindent 8 }}
        app: synthetic-pop
        app.kubernetes.io/name: controller
        component: synthetic-pop-controller
    spec:
      serviceAccountName: {{ template "synthetic-pop.controllerServiceAccountName" . }}
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/arch
                operator: In
                values:
                - {{ .Values.popArch }}
                {{- if .Values.controller.nodeSelector.enabled }}
              - key: {{ .Values.controller.nodeSelector.nodeLabel.key }}
                operator: In
                values:
                  - {{ .Values.controller.nodeSelector.nodeLabel.value }}
                {{- end }}
      {{- if .Values.controller.taintSelector.enabled }}
      tolerations:
        - key: {{ .Values.controller.taintSelector.nodeTaint.key }}
          operator: "Equal"
          value: {{ .Values.controller.taintSelector.nodeTaint.value }}
          effect: "PreferNoSchedule"
      {{- end }}
      imagePullSecrets:
        {{- if .Values.downloadKey }}
        - name: "instana-io"
        {{- else if .Values.downloadSecret }}
        - name: {{ .Values.downloadSecret }}
        {{- end }}
      {{- include "synthetic-pop.seccomp" . | nindent 6 }}
      containers:
      - name: synthetic-pop-controller
        image: {{ .Values.imagePath }}/{{ .Values.controller.image.name }}:{{ .Values.controller.image.tag }}
        imagePullPolicy: {{ .Values.controller.image.pullPolicy }}
        securityContext:
          privileged: false
          readOnlyRootFilesystem: true
          allowPrivilegeEscalation: false
          runAsNonRoot: true
          capabilities:
            drop:
              - ALL
        resources:
          limits:
            cpu: {{ .Values.controller.resources.limits.cpu }}
            memory: {{ .Values.controller.resources.limits.memory }}
          requests:
            cpu: {{ .Values.controller.resources.requests.cpu }}
            memory: {{ .Values.controller.resources.requests.memory }}
        volumeMounts:
          - mountPath: /opt/ibm/apm/pop/controller/logs
            name: logs
          - mountPath: /tmp
            name: tmp
          - name: instana-key
            mountPath: {{ template "instana.keyPath" . }}
            readOnly: true
          {{- if or (.Values.proxy.popProxyUserPass) (.Values.proxy.popProxyUserPassSecret) }}
          - name: proxy-user-pass
            mountPath: {{ template "proxy.userPassPath" . }}
            readOnly: true
          {{- end }}
          {{- if .Values.redis.tls.enabled }}
          - name: tls
            mountPath: {{ include "tls.certPath" . | quote }}
            readOnly: true
          {{- else }}
          - name: redis
            mountPath: {{ include "redis.passPath" . | quote }}
            readOnly: true
          {{- end }}
        livenessProbe:
          exec:
            command:
            - /opt/ibm/apm/pop/controller/synthetic-pop-controller.sh
            - health
          initialDelaySeconds: 240
          timeoutSeconds: 15
        readinessProbe:
          exec:
            command:
            - cat
            - /opt/ibm/apm/pop/controller/logs/pop.readiness
          initialDelaySeconds: 20
          periodSeconds: 10
        env:
        - name: LOCATION
          value: {{ .Values.controller.location | quote }}
        - name: POP_VER
          value: {{ .Chart.Version }}
        - name: PLAYBACK_CAPABILITIES
          value: {{ .Values.controller.capabilities | quote }}
        - name: CUSTOM_PROPERTIES
          value: {{ .Values.controller.customProperties | quote }}
        - name: HTTPACTION_PLAYBACK_URL
          value: "redis://synthetic-pop-redis:6378/0?ConfigurationQueue=HttpPlaybackConfigQueue&AARQueue=AARQueue"
        - name: HTTPSCRIPT_PLAYBACK_URL
          value: "redis://synthetic-pop-redis:6378/0?ConfigurationQueue=HttpScriptPlaybackConfigQueue&AARQueue=AARQueue"
        - name: WEBPAGEACTION_PLAYBACK_URL
          value: "redis://synthetic-pop-redis:6378/0?ConfigurationQueue=BrowserScriptPlaybackConfigQueue&AARQueue=AARQueue"
        - name: BROWSERSCRIPT_PLAYBACK_URL
          value: "redis://synthetic-pop-redis:6378/0?ConfigurationQueue=BrowserScriptPlaybackConfigQueue&AARQueue=AARQueue"
        - name: WEBPAGESCRIPT_PLAYBACK_URL
          value: "redis://synthetic-pop-redis:6378/0?ConfigurationQueue=BrowserScriptPlaybackConfigQueue&AARQueue=AARQueue"
        - name: DNSACTION_PLAYBACK_URL
          value: "redis://synthetic-pop-redis:6378/0?ConfigurationQueue=ISMPlaybackConfigQueue&AARQueue=AARQueue"
        - name: TLS_ENABLED
          value: {{ .Values.redis.tls.enabled | default false | quote }}
        {{- if .Values.redis.tls.enabled }}
        - name: CERTIFICATE_PATH
          value: {{ include "tls.certPath" . | quote }}
        {{- else }}
        - name: REDIS_PASSWORD_PATH
          value: {{ include "redis.passPath" . | quote }}
        {{- end }}
        # reserve this variable for container not supporting volume mount
        - name: REDIS_PASSWORD
          value: ""
        # reserve this variable for container not supporting volume mount
        - name: IRA_API_TENANT_ID
          value: ""
        - name: INSTANA_KEY_PATH
          value: {{ include "instana.keyPath" . | quote }}
        - name: TRACE_LEVEL
          value: {{ .Values.controller.traceLevel | default "INFO" | quote }}
        - name: JVM_ARGS
          value: "-Xms128M -Xmx128M -Xtune:virtualized"
        - name: INSTANA_ENDPOINT_URL
          value: {{ .Values.controller.instanaSyntheticEndpoint | quote }}
        # The max thread pool size for publishing result messages into Ingress service in parallel, default is 5
        - name: PUBLISHAAR_THREAD_POOL_SIZE
          value: {{ .Values.controller.publishAARThreadPoolSize | quote }}
        # The max thread pool size for scheduling tests and querying user credentials, default is 2
        - name: SCHEDULETEST_THREAD_POOL_SIZE
          value: {{ .Values.controller.scheduleTestMaxPoolSize | quote }}
        - name: CONFIGURATION_QUERY_INTERVAL
          value: "60"
        - name: CRED_EXPIRE_TIME
          value: {{ .Values.controller.credExpireTime | quote }}
        # Protocol for proxy server:  http | socks
        - name: POP_PROXY_PROTOCOL
          value: {{ .Values.proxy.popProxyProtocol | default "" | quote }}
        # PoP proxy server for communicating with instana backend server
        - name: POP_PROXY_SERVER
          value: {{ .Values.proxy.popProxyServer | default "" | quote }}
        # reserve this variable for container not supporting volume mount
        - name: POP_PROXY_AUTH
          value: ""
        {{- if or (.Values.proxy.popProxyUserPass) (.Values.proxy.popProxyUserPassSecret) }}
        - name: POP_PROXY_AUTH_PATH
          value: {{ include "proxy.userPassPath" . | quote }}
        {{- end }}
        - name: NAMESPACE
          value: {{ .Release.Namespace }}
        - name: CLUSTERNAME
          value: {{ .Values.controller.clusterName | quote }}
        - name: REDIS_NAMESPACE
          value: {{ .Values.controller.redisNamespace | quote }}
      volumes:
      - name: logs
        emptyDir: {}
      - name: tmp
        emptyDir: {}
      {{- if .Values.redis.tls.enabled }}
      - name: tls
        secret:
          secretName: {{ .Values.redis.tls.secretName | quote }}
          optional: false
      {{- else if .Values.redis.password }}
      - name: redis
        secret:
          secretName: {{ template "redis.secretName" . }}
          optional: false
      {{- else if .Values.redis.passwordSecret }}
      - name: redis
        secret:
          secretName: {{ .Values.redis.passwordSecret }}
          optional: false
      {{- end }}
      {{- if .Values.controller.instanaKeySecret }}
      - name: instana-key
        secret:
          secretName: {{ .Values.controller.instanaKeySecret }}
          optional: false
      {{- else }}
      - name: instana-key
        secret:
          secretName: {{ template "instanaKey.secretName" . }}
          optional: false
      {{- end}}
      {{- if .Values.proxy.popProxyUserPassSecret }}
      - name: proxy-user-pass
        secret:
          secretName: {{ .Values.proxy.popProxyUserPassSecret }}
          optional: false
      {{- else if .Values.proxy.popProxyUserPass }}
      - name: proxy-user-pass
        secret:
          secretName: {{ template "proxyUserPass.secretName" . }}
          optional: false
      {{- end }}
{{- end }}